### ISSUE TITLE
Not receiving Telegram

### ISSUE THREAD

**Issue by threeonparfive** [clickbg/homekit-monitord#15]
Is there a way to diagnose why I'm not receiving Telegram messages?  I just setup a Telegram account and followed the instructions here to get a bot token and private chat ID.  I used the test URL to verify that it's working and did receive the test message.  I then added the container variables for the token and chat ID received from following these instructions.  Upon container restart, I receive an email alert but no Telegram alert.

https://gist.github.com/nafiesl/4ad622f344cd1dc3bb1ecbe468ff9f8a

**Comment by threeonparfive** [comment]
I just found the manual run command in a closed issue (/usr/local/bin/monit2telegram.sh) which did work.  I'm just puzzled why I didn't get the notification when I started up the container and got the first couple of check-ins like I did via e-mail.  I would have assumed I'd get the same notifications through both email and telegram, more or less at the same time.

**Comment by clickbg** [comment]
Hi, this is a limitation in Monit. When the Monit service starts (on container restart) it send an email since it can only send emails for the daemon itself - there is no way to run a script on start up. This is described here - https://mmonit.com/monit/documentation/monit.html#ALERT-MESSAGES the 'set alert' option. The script you have found is only ever executed when the service itself - https://github.com/clickbg/homekit-monitord/blob/main/root/etc/monit/conf.d/homekit-active-hub-state.conf is either down or up but not on start up. You can fix that can put something like this:

`/usr/local/bin/sendtelegram.sh -c /etc/telegramrc -m "HomeKit-monitord is starting up"`

At the end of https://github.com/clickbg/homekit-monitord/blob/main/root/docker-entrypoint.d/99-homekit-monitoring-config.sh after:

`/etc/init.d/monit restart`

~~I could possibly make that an additional option in the compose file if you prefer? Something like ADDON_SCRIPTS="" that gets executed on startup?~~

I have updated the container to send Telegram notifications on startup with https://github.com/clickbg/homekit-monitord/pull/16 could you please pull the latest Docker image and verify?

Thanks!

**Comment by threeonparfive** [comment]
By the time I woke up and saw this, my Watchtower had already upgraded it and I do see the startup alert in Telegram.  Thanks so much!!!
